import { ActivityInterface } from '../core/activity.model';

export const MOCK_ACTIVITIES: ActivityInterface[] = [
  {
    id: 1,
    name: 'Ankara Anıtkabir Gezisi',
    startDate: '2026-10-29',
    endDate: '2026-10-30',
    activityType: 'Gezi',
    isPaid: true,
    fee: 1500,
    status: 'Aktif',
    requestStartDate: '2026-09-01',
    requestEndDate: '2026-10-15',
    isParentRequired: true,
    description: 'Cumhuriyet Bayramı özel Ankara gezisi.',
    maxStudentCount: 45,
    studentParentCount: 1,
    transportation: 'Otobüs',
    eventManager: 'Ahmet Yılmaz',
    oKod1: '',
    oKod2: '',
    oKod3: '',
    oKod4: '',
    oKod5: '',
    xSicilID: 101,
    createdAt: '2026-07-27',
    isPrivate: false,
    classroom: 'Tüm Sınıflar',
  },
  {
    id: 2,
    name: 'Geleneksel Pilav Günü',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    activityType: 'Sosyal Etkinlik',
    isPaid: false,
    fee: null,
    status: 'Aktif',
    requestStartDate: '2026-07-01',
    requestEndDate: '2026-08-10',
    isParentRequired: false,
    description: 'Mezunlar ve mevcut öğrenciler için pilav günü.',
    maxStudentCount: 500,
    studentParentCount: 2,
    transportation: 'Bireysel',
    eventManager: 'Fatma Kaya',
    oKod1: '',
    oKod2: '',
    oKod3: '',
    oKod4: '',
    oKod5: '',
    xSicilID: 102,
    createdAt: '2026-07-20',
    isPrivate: false,
    classroom: 'Tüm Sınıflar',
  },
];
